synology:
  url: "http://192.168.1.3:5000"
  username: "bot"
  password: "yWB33lpB123"  # замените на реальный пароль
  
  # Маппинг категорий на пути в Download Station
  paths:
    movie: "downloads/movie"
    cartoon: "downloads/video/movies/cartoons"
    shows: "downloads/video/shows/main"
    audiobook: "downloads/audiobook"
    other: "downloads/other"
    shows_cartoons: "downloads/video/shows/cartoons"

mcore:
  addr: "https://t.a3b.me/api/"
  secret: "tokenOnlyForTest20260117_fdfhkflgkh#djksdfDDs21"

debug: true
